name: Automatic build

on:
  push:
      brances: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run:  sudo apt install zopfli

    - name: Build x86_64 (all compression, DwarFS)
      run:  COMPRESS_SQUASHFUSE=1 img_type=dwarfs ARCH=x86_64 ./make_runtime.sh

    - name: Build all architectures (LZ4)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=x86_64-aarch64-armhf ./make_runtime.sh

    - name: Build x86_64 and aarch64 (LZ4)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=x86_64-aarch64 ./make_runtime.sh
  
    - name: Build x86_64 (LZ4)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=x86_64 ./make_runtime.sh
  
    - name: Build aarch64 (LZ4)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=aarch64 ./make_runtime.sh

    - name: Build armhf (LZ4)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=armhf ./make_runtime.sh
  
    - name: Build all architectures (ZSTD)
      run:  rm -r squashfuse; COMPRESS_SQUASHFUSE=1 ARCH=x86_64-aarch64-armhf COMP=zstd ./make_runtime.sh

    - name: Build x86_64 and aarch64 (ZSTD)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=x86_64-aarch64 COMP=zstd ./make_runtime.sh
  
    - name: Build x86_64 (ZSTD)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=x86_64 COMP=zstd ./make_runtime.sh
  
    - name: Build aarch64 (ZSTD)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=aarch64 COMP=zstd ./make_runtime.sh

    - name: Build armhf (ZSTD)
      run:  COMPRESS_SQUASHFUSE=1 ARCH=armhf COMP=zstd ./make_runtime.sh

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous"
        files: |
          runtime-*
          runtime_*
