name: Automatic build

on:
  push:
      brances: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build all architectures (LZ4)
      run:  ARCH=x86_64-aarch64-armhf ./mkruntime

    - name: Build x86_64 and aarch64 (LZ4)
      run:  ARCH=x86_64-aarch64 ./mkruntime
  
    - name: Build x86_64 (LZ4)
      run:  ARCH=x86_64 ./mkruntime
  
    - name: Build aarch64 (LZ4)
      run:  ARCH=aarch64 ./mkruntime

    - name: Build armhf (LZ4)
      run:  ARCH=armhf ./mkruntime
  
    - name: Build all architectures (ZSTD)
      run:  ARCH=x86_64-aarch64-armhf COMP=zstd ./mkruntime

    - name: Build x86_64 and aarch64 (LZ4)
      run:  ARCH=x86_64-aarch64 COMP=zstd ./mkruntime
  
    - name: Build x86_64 (LZ4)
      run:  ARCH=x86_64 COMP=zstd ./mkruntime
  
    - name: Build aarch64 (LZ4)
      run:  ARCH=aarch64 COMP=zstd ./mkruntime

    - name: Build armhf (LZ4)
      run:  ARCH=armhf COMP=zstd ./mkruntime

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous"
        files: |
          runtime-*
